app:
    useFakeCustomerRepo: true
info:
    app:
        description: Learning Spring Boot
        name: SpringBootAdvancedIsh
        version: 1.0.0
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    server:
        port: 9999
server:
    error:
        include-binding-errors: always
        include-message: always
    port: 7777
spring:
    application:
        name: SpringBootAdvancedIsh
    datasource:
        driver-class-name: org.h2.Driver
        password: password
        url: jdbc:h2:mem:test_db-dev-environment
        username: yordan
    h2:
        console:
            enabled: true
            path: /h2-dev
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
